Bug found when compiling SpecBit with gcc v8
When compiling SpecBit with GCC c++ v8.1.0 errors occur with template
specialisation such as the one below:

<path to installation>/gambit/SpecBit/include/gambit/SpecBit/MSSMSpec_head.hpp:50:11:
error: too many template-parameter-lists
struct SpecTraits<SpecBit::MSSMSpec<MI>>
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The code can be made to compile and run by removing unecessary template
specialisations, such as the diff below:

diff --git a/SpecBit/include/gambit/SpecBit/MSSMSpec_head.hpp b/SpecBit/include/gambit/SpecBit/MSSMSpec_head.hpp
index f2b2a0c8d..5100d498e 100644
--- a/SpecBit/include/gambit/SpecBit/MSSMSpec_head.hpp
+++ b/SpecBit/include/gambit/SpecBit/MSSMSpec_head.hpp
@@ -45,7 +45,6 @@ namespace Gambit

    /// Specialisation of "traits" class used to inform Spec<T> class of what
    /// "Model" and "Input" are for this derived class
-   template <>
    template <class MI>
    struct SpecTraits<SpecBit::MSSMSpec<MI>>
    {

These modifications need to be tested on older compilers before merging
into the main branch.